import Head from 'next/head';
import 'semantic-ui-css/semantic.min.css';
import Navbar from "./componenent/Navbar";
import { useState } from 'react';
import 'react-calendar/dist/Calendar.css';

export default function Home() {
    const [nombre, setNombre] = useState(0); // État pour le nombre de formulaires à afficher
    const [formulaires, setFormulaires] = useState([]); // État pour stocker les formulaires

    const handleChange = (e) => {
        const value = parseInt(e.target.value);
        setNombre(value); // Mettre à jour le nombre de formulaires à afficher
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        // Générer les formulaires en fonction du nombre sélectionné
        const nouveauxFormulaires = [];
        for (let i = 0; i < nombre; i++) {
            nouveauxFormulaires.push(
                <div style={{backgroundColor: "#FFFFFF0F", margin:"1%", padding:"1%", borderRadius:"20px", textAlign:"center"}}>
                <form  key={i}>
                    <h3> {i+1} </h3>

                    <label>Entrée:</label>
                    <input
                        type="entrée"
                        onChange={(e) => setEmail(e.target.value)}

                    />
                    <label>plat:</label>
                    <input
                        type="plat"
                        onChange={(e) => setEmail(e.target.value)}

                    />
                    <label>vins:</label>
                    <input
                        type="vins"
                        onChange={(e) => setEmail(e.target.value)}

                    />
                    <label>dessert:</label>
                    <input
                        type="dessert"
                        onChange={(e) => setEmail(e.target.value)}

                    />

                </form>
                </div>
            );
        }
        setFormulaires(nouveauxFormulaires); // Mettre à jour les formulaires affichés
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <div>
                    <Navbar />
                    <div style={{ color: "white", textAlign: "center", alignItems:"center" }}>
                        <h2>Combien êtes-vous ?</h2>
                        <form onSubmit={handleSubmit}>
                            <input
                                type="number"
                                value={nombre}
                                onChange={handleChange}
                                max={5}
                                min={0}
                            />
                            <button type="submit">Soumettre</button>
                        </form>
                        <div className="formulaire" >
                        {formulaires } {/* Affiche les formulaires générés */}
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
