import Head from 'next/head'
import 'semantic-ui-css/semantic.min.css'
import Navbar from "./componenent/Navbar.js"
import Section from "./componenent/section.js"
import BlurCard from "./componenent/BlurCard.js"


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <div style={{margin:"0", padding:"0",top:"0", backgroundImage:"url('/resto.jpg')",backgroundSize: "cover",minHeight:"10vh",height: "auto",}}>
                    <Navbar/>
                    <div className="Fond">
                        <button style={{marginBottom:"10px", marginTop:"20px",fontFamily:"Whisper", fontSize:"30px", color:"white", backgroundColor:"transparent", borderStyle:"none", padding:"15px", borderTop:"solid white", borderBottom:"solid white",}}>
                        <a  href={"./reserver"} style={{color:"white"}}>   Faire une réservation </a>
                        </button>
                        <hr style={{marginBottom:"10px", marginRight:'47%', marginLeft:"47%"}}/>
                    </div>
                </div>
                <div style={{textAlign:"center",margin:"40px",paddingTop:"0", padding:"10px", marginBottom:"100px", fontSize:"20px", color :"white"}}>
                    <hr style={{marginBottom:"10px", marginRight:'0', marginLeft:"0"}}/>
                    <p style={{fontSize:"40px", marginRight:'2%', marginLeft:"2%",marginBottom:"0", fontFamily:"Whisper",}}>Brasserie Fouquet's</p>
                    <p>Depuis 1899, la Brasserie Fouquet’s vit au rythme de la capitale de l’art de vivre, célèbre son esprit parisien et met sa gastronomie à l’honneur. Au croisement des Champs-Elysées et de l’avenue George-V, ses auvents rouges aux lettres d'or imposent sa signature et abritent deux terrasses, où le Tout-Paris s’attable. Un subtil mélange de raffinement et de glamour. L’entrée donne le ton, pavée de plaques en l’honneur d’acteurs célèbres qui nous rappellent qu’on marche ici sur les pas des stars du septième art. A l’intérieur, les portraits des icônes du cinéma s’affichent en clair-obscur, signés par l’incontournable studio Harcourt. Révisant ses classiques, Pierre Gagnaire signe une carte en osmose avec l’atmosphère authentique des lieux, où les ronds de serviettes attendent chaque hôte - encore un clin d'œil à l’esprit maison de famille. L’escargot, la sole meunière ou encore le millefeuille, issus du répertoire traditionnel de la gastronomie française, y sont réinterprétés avec malice.</p>
                    <hr style={{marginBottom:"10px", marginRight:'40%', marginLeft:"40%"}}/>
                </div>
                <Section/>
                <hr style={{marginTop:"100px", marginBottom:"20px", marginRight:'2%', marginLeft:"2%"}}/>
                <div style={{margin:"0", padding:"0",top:"0", backgroundImage:"url('/endpage1.png')",backgroundSize: "cover",minHeight:"100vh",height: "auto",}}>
                    <div className="inverseFond">
                        <BlurCard/>
                    </div>
                </div>




            </main>
        </>

    )
}



