import Head from 'next/head'
import 'semantic-ui-css/semantic.min.css'
import Navbar from "./componenent/Navbar";
import {Divider} from "semantic-ui-react";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

            </Head>
            <main>
            <div>
                    <Navbar/>

                <Divider horizontal style={{marginTop:"10px", marginLeft:"10px", marginRight:"10px"}}>
                    <p style={{color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px"}}>MENU</p>
                </Divider>

                <div>
                    <p style={{marginTop:"40px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>ENTRÉE</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>.</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>PLAT</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>.</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>DESSERT</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>.</p>
                    <p style={{marginTop:"10px",color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px", textAlign:"center"}}>VINS</p>
                </div>
            </div>
            </main>



        </>
    )
}
