import Head from 'next/head';
import 'semantic-ui-css/semantic.min.css';
import Navbar from "./componenent/Navbar";
import { Divider } from 'semantic-ui-react';
import Calendar from 'react-calendar';
import { useState } from 'react';
import 'react-calendar/dist/Calendar.css';
import styles from '../styles/calendar.module.css';
import Reservation from './componenent/horaire.js'


export default function Home() {
    const [selectedDate, setSelectedDate] = useState(null);

    const handleDateChange = (date) => {
        setSelectedDate(date);
    };

    const formatDate = (date) => {
        const options = { day: 'numeric', month: 'long', year: 'numeric', locale: 'fr' };
        return new Intl.DateTimeFormat('fr', options).format(date);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <div style={{
                    margin: "0",
                    padding: "0",

                    backgroundSize: "cover",
                    minHeight: "100vh",
                    height: "auto"
                }}>
                    <Navbar/>
                    <Divider horizontal style={{marginTop: "100px", marginLeft: "10px", marginRight: "10px"}}>
                        <p className="title">Faire Une Réservation</p>
                    </Divider>
                    <div className="reservation" >
                    <div style={{margin:0}}>
                    <Calendar
                        onChange={handleDateChange}
                        value={selectedDate}
                        className={styles['react-calendar']}
                        locale="fr-FR"

                    />
                    {selectedDate && (
                        <div>
                        <p style={{ color: "white" }}>Vous avez sélectionné : {formatDate(selectedDate)}</p>
                        <Reservation selectedDate={selectedDate}/>
                            </div>
                    )}
                    </div>
                    </div>
                </div>
            </main>
        </>
    );
}
