import Head from 'next/head'
import 'semantic-ui-css/semantic.min.css'
import Navbar from "./componenent/Navbar";
import { Divider } from 'semantic-ui-react'
import Calendrier from "./componenent/Calendar";
export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

            </Head>
            <main>

                <div style={{margin:"0", padding:"0", backgroundImage:"url('/Reservation.png')",backgroundSize: "cover",minHeight:"100vh",height: "auto",}}>
                    <Navbar/>
                    <Divider horizontal style={{marginTop:"100px", marginLeft:"10px", marginRight:"10px"}}>
                        <p style={{color:"White",fontFamily:"Whisper",fontStyle: "Regular", fontSize:"32px"}}>Faire  Une  Réservation</p>
                    </Divider>
                    <Calendrier/>
                </div>
            </main>



        </>
    )
}
